install.packages("palmerpenguins")
install.packages("here")

require(palmerpenguins)
require(here)
library("palmerpenguins")
class(penguins)
penguins = data.frame(penguins)
mean(penguins$body_mass_g, na.rm = TRUE)
head(penguins)
na.rm = TRUE
summary(penguins)
boxplot(penguins$bill_depth_mm)
par(mfrow = c(1, 2))
boxplot(penguins$bill_depth_mm)
boxplot(bill_depth_mm ~ sex, data = penguins)
par(mfrow = c(2, 3))
boxplot(bill_depth_mm ~ sex, data = penguins)
coplot(flipper_length_mm ~ bill_depth_mm | island, data = penguins, rows = 1)
